#!/bin/sh
xrandr --output eDP-1 --mode 2560x1440 --pos 0x720 --rotate normal --output DP-1 --primary --mode 3840x2160 --pos 2560x0 --rotate normal --output DP-2 --off --output DP-3 --off
feh --randomize --bg-fill ~/.wallpapers/*
